### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by phipsgabler** [phipsgabler/DynamicComputationGraphs.jl#12]
Now that tracking basically works, here are the next steps I plan to take; approximately in that order (except test cases, hopefully):

- [x] Refactor tracking (with new `TrackBuilder`)
- [x] Go over exports and imports
- [x] Add docstrings
- [x] Better custom representation of expressions (capturing actual functions, save space by referring to original IR)
- [x] Add context-based dispatch for `record!`, allowing to define when to recurse
- [x] Add more metadata to graph (locations, variable names?, types?); allow context-specific metadata recording
- [x] Improve API for handling `GraphTape` -- iteration, extract data path, backward passes, metadata analysis, etc. (See #20)
- [x] Test cases: 
  - [x] Some very simple runs to check proper compilation and working IR conversion
  - [x] Backward-mode AD, testing against ~FiniteDifferences.jl~ Zygote (basically #2)
  - [x] Turing models in #7. 
- [x] Conversion to `MetaGraph`, and by that allow GraphViz export

CC @trappmartin @yebai

**Comment by trappmartin** [comment]
Looks good to me.

Could you elaborate on context-based dispatch. Some details on the issue and how you plan to approach it.

Regarding metadata, maybe you could use a metadata type and have a vector? or Dict? of metadata as field on each node?  Or some other approach that let’s the metadata be pretty much everything.

**Comment by phipsgabler** [comment]
Ad context-based dispatch: I'm thinking about doing something very similar to [Cassette](https://jrevels.github.io/Cassette.jl/stable/overdub.html), where you define a type for the context, and can overload a couple of methods based on that to do special things; among them some functions to be used in `record!`.  One which decides whether to recurse, and one other which can record arbitrary metadata (although the latter might also be necessary to work in other places than just `record!`, I don't know yet.

Ad metadata: there's already this [StatementInfo](https://github.com/phipsgabler/DynamicComputationGraphs.jl/blob/master/src/graph.jl#L7) field in every node, currently completely unused (so putting data at anything and anywhere was always my plan). The question remaining are what to put in there, and how/where to do that.

By the way, just so that you guys know: I'll be away and off-grid from 18. to 29.09., so starting to work on that again on Monday the 30.

**Comment by phipsgabler** [comment]
Update: I'm working on it, but needed to restructure a lot of code to be able to implement contexts and better expression representations cleanly.

A bit of the graph API is there (`children`, `parents`, `backward`, and iterator methods), but most of I expect to implement on demand for test cases.
